services:
  redis:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - wiki-network

  springboot:
    container_name: server
    image: ${DOCKERHUB_USERNAME}/wiki-server:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - LOG_PATH=/logs
    volumes:
      - ./server/logs:/logs
    depends_on:
      - redis
    networks:
      - wiki-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
    - ./prometheus:/etc/prometheus:ro
    - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
    networks:
      - wiki-network

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - wiki-network

networks:
  wiki-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
