services:
  redis:
    container_name: redis
    image: redis:7.4
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - runner-wiki-network
  kafka:
    container_name: kafka
    image: apache/kafka:3.8.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    restart: unless-stopped
    ports:
      - 9092:9092
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    networks:
      - runner-wiki-network
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.15
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - ./meilisearch/data:/meili_data
    networks:
      - runner-wiki-network
  springboot:
    container_name: springboot
    image: ${DOCKERHUB_USERNAME}/wiki-server:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./springboot/logs:/logs
    depends_on:
      - redis
      - kafka
      - meilisearch
    networks:
      - runner-wiki-network

networks:
  runner-wiki-network:
    driver: bridge
