### 문서 목록 조회 V1 (오프셋)
GET http://localhost:8080/api/v1/documents?category=all&page=500000&size=15

### 문서 목록 조회 V2 (커버링 인덱스)
GET http://localhost:8080/api/v2/documents?category=all&page=500000&size=15